In [ ]:
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier¶

Predict trophies
based on cards, achievements,badges, total games, total donations
use combined_player_tags.csv and drop null columns, drop '/player_tag, drop urls,

In [1]:
import os
import json
import numpy as np
import pandas as pd

# Set the file path for the JSON file
json_file_path = os.path.join('..', 'Resources', 'combined_player_tags.json')

# Check if the file exists
if os.path.exists(json_file_path):
    # Open and load the JSON data
    with open(json_file_path) as fp:
        player_data = json.load(fp)
        # Process player_data as needed
else:
    print("File not found:", json_file_path)

In [2]:
player_data_wide_df = pd.json_normalize(player_data)
player_data_wide_df.head()

,player_tag,data.tag,data.name,data.expLevel,data.trophies,data.bestTrophies,data.wins,data.losses,data.battleCount,data.threeCrownWins,...,data.lastPathOfLegendSeasonResult.rank,data.bestPathOfLegendSeasonResult.leagueNumber,data.bestPathOfLegendSeasonResult.trophies,data.bestPathOfLegendSeasonResult.rank,data.currentFavouriteCard.maxEvolutionLevel,data.currentFavouriteCard.iconUrls.evolutionMedium,data.leagueStatistics.previousSeason.id,data.leagueStatistics.previousSeason.trophies,data.leagueStatistics.previousSeason.bestTrophies,data.leagueStatistics.bestSeason.rank
0,%23LV0LV,#LV0LV,FAJRI JR,5,676,857,73,97,173,56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,%238R80YP,#8R80YP,<c7>omeganike</,37,5492,5671,3382,3359,7821,1193,...,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,%23R0VJQ,#R0VJQ,jonas123,10,1954,2235,405,437,886,263,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,%23JRRULRR9C,#JRRULRR9C,samuel,4,377,423,25,30,56,9,...,NaN,NaN,NaN,NaN,1.0,https://api-assets.clashroyale.com/cardevoluti...,NaN,NaN,NaN,NaN
4,%23QRJVULQQ9,#QRJVULQQ9,ash,8,3775,3848,155,153,309,49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN